# Generated by Django 4.2.3 on 2023-09-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('bio', models.TextField(max_length=500)),
                ('avatar_image', models.URLField()),
                ('background_image', models.URLField()),
                ('is_active', models.BooleanField()),
                ('date_created', models.DateTimeField()),
                ('kms_goal', models.IntegerField()),
                ('kms_ridden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('anonymous', models.BooleanField()),
                ('donor', models.CharField(max_length=200)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='riders.rider')),
            ],
        ),
    ]
