# Generated by Django 4.2.3 on 2023-09-06 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riders', '0002_rider_rider_owner_alter_donation_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='kms_ridden',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='riders.rider'),
        ),
        migrations.CreateModel(
            name='RiderUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kms_ridden', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=300)),
                ('image', models.URLField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_updates', to='riders.rider')),
            ],
        ),
    ]
