# Generated by Django 4.2.3 on 2023-09-06 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riders', '0003_remove_rider_kms_ridden_alter_donation_donor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='rider_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
