# Generated by Django 4.2.3 on 2023-09-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_alter_rider_rider_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='kms_goal',
            new_name='dollar_goal',
        ),
        migrations.AddField(
            model_name='rider',
            name='kms_ceiling',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, '1km'), (2, '2km'), (5, '5km')], default=1, help_text='How may kms would you like to ride for each $ donated?'),
        ),
    ]
