# Generated by Django 4.2.3 on 2023-09-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0005_rename_kms_goal_rider_dollar_goal_rider_kms_ceiling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='dollar_goal',
        ),
    ]
