# Generated by Django 4.2.3 on 2023-09-08 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0006_remove_rider_dollar_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderupdates',
            name='rider',
        ),
        migrations.AddField(
            model_name='riderupdates',
            name='rider_owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rider', to='riders.rider'),
            preserve_default=False,
        ),
    ]
