# Generated by Django 4.2.3 on 2023-09-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0007_remove_riderupdates_rider_riderupdates_rider_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='kms_ridden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
