# Generated by Django 4.2.3 on 2023-09-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0008_rider_kms_ridden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='kms_ridden',
        ),
    ]
